/**
 * Drafts an information-blocking complaint for a vendor that missed a
 * statutory deadline.
 *
 * This produces a draft for a human to read, edit, and decide whether to file.
 * Filing a complaint against a prospective business partner is a consequential
 * step and is never automated -- but having the draft ready, with the dates
 * already correct, means the decision is about whether to escalate rather than
 * about whether anyone can be bothered to assemble the evidence.
 *
 * Complaints go to the ONC Health IT Feedback and Inquiry Portal.
 */

import type { ClockResult } from './businessDays.ts';

export const ONC_PORTAL = 'https://inquiry.healthit.gov/support/plugins/servlet/loginfreeRedirMain?portalid=2';

export interface ComplaintInput {
  vendorName: string;
  chplDeveloperId: string;
  certifiedCriteria: string[];
  requestSent: string;
  verificationCompleted?: string | null;
  clock: ClockResult;
  requesterEntity: string;
  requesterContact: { name: string; email: string };
  /** Anything the vendor said or failed to say, in the operator's own words. */
  correspondenceSummary?: string;
}

export function draftComplaint(input: ComplaintInput): string {
  const b = input.clock.breach;
  if (!b) {
    throw new Error('draftComplaint called for a request that is not in breach.');
  }

  const stageText =
    b.stage === 'verification'
      ? `complete authenticity verification within ten business days of receiving our registration request`
      : `register and enable our application for production use within five business days of completing authenticity verification`;

  return `# Information blocking complaint — draft

**DRAFT. Not filed. Review before submitting.**

Submit at: ${ONC_PORTAL}

---

## Complainant

${input.requesterEntity}
${input.requesterContact.name} — ${input.requesterContact.email}

## Subject of complaint

${input.vendorName} (CHPL developer ID ${input.chplDeveloperId})
Certified to: ${input.certifiedCriteria.join(', ') || '(not recorded)'}

## Nature of the concern

${input.vendorName} is a Certified API Developer subject to the API Condition and
Maintenance of Certification at 45 CFR 170.404. It appears not to have met the
obligation under ${b.citation} to ${stageText}.

## Timeline

| Event | Date |
| --- | --- |
| Registration request received by ${input.vendorName} | ${input.requestSent} |
${input.verificationCompleted ? `| Authenticity verification completed | ${input.verificationCompleted} |\n` : ''}| Deadline under ${b.citation} | ${b.deadline} |
| Business days elapsed past deadline | ${b.businessDaysOverdue} |

Deadlines are calculated in business days, excluding weekends and US federal
holidays.

${input.correspondenceSummary ? `## Correspondence\n\n${input.correspondenceSummary}\n` : `## Correspondence\n\n_Summarize what was sent, what response was received, and any follow-up. Attach the registration request and any vendor replies._\n`}

## Relief sought

That ${input.vendorName} complete the outstanding step and register and enable the
application for production use as required by 45 CFR 170.404(b)(1).

---

## Before filing — check each

- [ ] The registration request was actually received on the date stated (have the send confirmation)
- [ ] The request was submitted through the vendor's own published process
- [ ] The request was complete as published — an incomplete submission does not start the clock
- [ ] Any vendor response asking for more information is accounted for in the timeline
- [ ] Escalating is the right move commercially, not only the right move regulatorily

_Draft generated by the EHR Integration Management System._
`;
}
